// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZR9SUbv_b30Hc8cTr9kFK97AXy2U98hM',
    appId: '1:1078708428195:web:7e9ff2fce31ce5fd2e8e16',
    messagingSenderId: '1078708428195',
    projectId: 'quickpitch-e3395',
    authDomain: 'quickpitch-e3395.firebaseapp.com',
    storageBucket: 'quickpitch-e3395.firebasestorage.app',
    measurementId: 'G-R4TV9391LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpj0FSem-7qbOubL-ETZpwjtgOMeVdZac',
    appId: '1:1078708428195:android:fd69fd54c76597992e8e16',
    messagingSenderId: '1078708428195',
    projectId: 'quickpitch-e3395',
    storageBucket: 'quickpitch-e3395.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUPBhJ6lwyn7cC4W6bjr0bpb_cyXuA2ok',
    appId: '1:1078708428195:ios:9181cd95f488dc862e8e16',
    messagingSenderId: '1078708428195',
    projectId: 'quickpitch-e3395',
    storageBucket: 'quickpitch-e3395.firebasestorage.app',
    androidClientId: '1078708428195-v7npuno3655ur5v4mkis6e1932o1c19a.apps.googleusercontent.com',
    iosClientId: '1078708428195-orcm6nmshhqsde7l2su7rajsi4kv9oql.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickpitchWwwweb',
  );
}
